workflows:
  android-release:
    name: Android Release Build
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      groups:
        - keystore_credentials
      vars:
        PACKAGE_NAME: "com.superpartybyai.superparty_app"
    scripts:
      - name: Set up key.properties
        script: |
          echo "storePassword=$CM_KEYSTORE_PASSWORD" > $CM_BUILD_DIR/superparty_flutter/android/key.properties
          echo "keyPassword=$CM_KEY_PASSWORD" >> $CM_BUILD_DIR/superparty_flutter/android/key.properties
          echo "keyAlias=$CM_KEY_ALIAS" >> $CM_BUILD_DIR/superparty_flutter/android/key.properties
          echo "storeFile=$CM_KEYSTORE_PATH" >> $CM_BUILD_DIR/superparty_flutter/android/key.properties
      - name: Get Flutter packages
        script: |
          cd superparty_flutter
          flutter packages pub get
      - name: Build APK
        script: |
          cd superparty_flutter
          flutter build apk --release
      - name: Build AAB
        script: |
          cd superparty_flutter
          flutter build appbundle --release
    artifacts:
      - superparty_flutter/build/app/outputs/flutter-apk/*.apk
      - superparty_flutter/build/app/outputs/bundle/release/*.aab
    publishing:
      email:
        recipients:
          - your-email@example.com
