import '../models/event_model.dart';

/// Mock service pentru evenimente (pentru MVP)
class MockEventService {
  static List<EventModel> getMockEvents() {
    final now = DateTime.now();
    
    return [
      EventModel(
        id: '01',
        date: '15-01-2026',
        address: 'Bucuresti, Sector 3, acasa',
        cineNoteaza: 'A1',
        sofer: 'D1',
        soferPending: '',
        sarbatoritNume: 'Maria',
        sarbatoritVarsta: 5,
        sarbatoritDob: '10-02-2020',
        incasare: IncasareModel(
          status: 'INCASAT',
          metoda: 'CASH',
          suma: 490,
        ),
        roles: [
          RoleModel(
            slot: 'A',
            label: 'Batman',
            time: '14:00',
            durationMin: 120,
            assignedCode: 'A3',
            pendingCode: '',
          ),
        ],
        createdAt: now.subtract(const Duration(days: 5)),
        createdBy: 'system',
        updatedAt: now.subtract(const Duration(days: 5)),
        updatedBy: 'system',
      ),
      EventModel(
        id: '02',
        date: '20-01-2026',
        address: 'Cluj-Napoca, local',
        cineNoteaza: 'B7',
        sofer: '',
        soferPending: '',
        sarbatoritNume: 'Andrei',
        sarbatoritVarsta: 6,
        sarbatoritDob: '03-06-2019',
        incasare: IncasareModel(
          status: 'AVANS',
          metoda: 'TRANSFER',
          suma: 250,
        ),
        roles: [
          RoleModel(
            slot: 'A',
            label: 'Spiderman',
            time: '18:30',
            durationMin: 120,
            assignedCode: '',
            pendingCode: '',
          ),
        ],
        createdAt: now.subtract(const Duration(days: 3)),
        createdBy: 'system',
        updatedAt: now.subtract(const Duration(days: 3)),
        updatedBy: 'system',
      ),
      EventModel(
        id: '03',
        date: '28-01-2026',
        address: 'Iasi, sala',
        cineNoteaza: 'A12',
        sofer: 'C3',
        soferPending: '',
        sarbatoritNume: 'Sofia',
        sarbatoritVarsta: 4,
        sarbatoritDob: '14-09-2021',
        incasare: IncasareModel(
          status: 'NEINCASAT',
          metoda: 'CASH',
          suma: 840,
        ),
        roles: [
          RoleModel(
            slot: 'A',
            label: 'Elsa',
            time: '16:00',
            durationMin: 120,
            assignedCode: 'B12',
            pendingCode: '',
          ),
        ],
        createdAt: now.subtract(const Duration(days: 1)),
        createdBy: 'system',
        updatedAt: now.subtract(const Duration(days: 1)),
        updatedBy: 'system',
      ),
      EventModel(
        id: '04',
        date: '05-02-2026',
        address: 'Ploiesti, acasa',
        cineNoteaza: 'C1',
        sofer: '',
        soferPending: 'D7',
        sarbatoritNume: 'Daria',
        sarbatoritVarsta: 7,
        sarbatoritDob: '22-12-2018',
        incasare: IncasareModel(
          status: 'AVANS',
          metoda: 'CASH',
          suma: 300,
        ),
        roles: [
          RoleModel(
            slot: 'A',
            label: 'Printesa',
            time: '12:00',
            durationMin: 120,
            assignedCode: 'A1',
            pendingCode: '',
          ),
          RoleModel(
            slot: 'B',
            label: 'Vata de zahar',
            time: '12:30',
            durationMin: 90,
            assignedCode: '',
            pendingCode: 'B2',
          ),
        ],
        createdAt: now.add(const Duration(days: 5)),
        createdBy: 'system',
        updatedAt: now.add(const Duration(days: 5)),
        updatedBy: 'system',
      ),
      EventModel(
        id: '05',
        date: '18-01-2026',
        address: 'Bucuresti, Sector 2, sala',
        cineNoteaza: 'A3',
        sofer: '',
        soferPending: '',
        sarbatoritNume: 'Rares',
        sarbatoritVarsta: 5,
        sarbatoritDob: '01-03-2020',
        incasare: IncasareModel(
          status: 'INCASAT',
          metoda: 'CARD',
          suma: 490,
        ),
        roles: [
          RoleModel(
            slot: 'A',
            label: 'Batman',
            time: '11:00',
            durationMin: 120,
            assignedCode: 'A1',
            pendingCode: '',
          ),
        ],
        createdAt: now.subtract(const Duration(days: 2)),
        createdBy: 'system',
        updatedAt: now.subtract(const Duration(days: 2)),
        updatedBy: 'system',
      ),
      EventModel(
        id: '06',
        date: '22-01-2026',
        address: 'Brasov, local',
        cineNoteaza: 'B12',
        sofer: '',
        soferPending: '',
        sarbatoritNume: 'Elena',
        sarbatoritVarsta: 6,
        sarbatoritDob: '08-11-2019',
        incasare: IncasareModel(
          status: 'NEINCASAT',
          metoda: 'CASH',
          suma: 840,
        ),
        roles: [
          RoleModel(
            slot: 'A',
            label: 'Elsa',
            time: '15:00',
            durationMin: 120,
            assignedCode: '',
            pendingCode: '',
          ),
        ],
        createdAt: now.add(const Duration(days: 2)),
        createdBy: 'system',
        updatedAt: now.add(const Duration(days: 2)),
        updatedBy: 'system',
      ),
      EventModel(
        id: '07',
        date: '25-01-2026',
        address: 'Constanta, acasa',
        cineNoteaza: 'C7',
        sofer: 'A0',
        soferPending: '',
        sarbatoritNume: 'Matei',
        sarbatoritVarsta: 8,
        sarbatoritDob: '19-07-2017',
        incasare: IncasareModel(
          status: 'AVANS',
          metoda: 'TRANSFER',
          suma: 400,
        ),
        roles: [
          RoleModel(
            slot: 'A',
            label: 'Ursitoare',
            time: '19:00',
            durationMin: 30,
            assignedCode: '',
            pendingCode: '',
          ),
        ],
        createdAt: now.add(const Duration(days: 5)),
        createdBy: 'system',
        updatedAt: now.add(const Duration(days: 5)),
        updatedBy: 'system',
      ),
    ];
  }
}
